/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "secondary": "#f68a2f",
        "surface-variant": "#262626",
        "on-surface": "#ffffff",
        "error": "#ff6e84",
        "inverse-on-surface": "#565555",
        "on-secondary-fixed": "#552800",
        "outline": "#767575",
        "inverse-primary": "#ab3628",
        "on-tertiary-fixed": "#2b1600",
        "surface-container-high": "#20201f",
        "on-error-container": "#ffb2b9",
        "primary-dim": "#fe735f",
        "on-primary": "#650100",
        "tertiary": "#ffb158",
        "on-tertiary-container": "#4c2b00",
        "background": "#0e0e0e",
        "tertiary-fixed-dim": "#ed9000",
        "on-primary-container": "#4f0100",
        "secondary-fixed": "#ffc69f",
        "secondary-fixed-dim": "#ffb37c",
        "tertiary-dim": "#ed9000",
        "surface-container-highest": "#262626",
        "secondary-dim": "#ec8327",
        "inverse-surface": "#fcf9f8",
        "on-tertiary": "#5a3400",
        "surface-container": "#1a1a1a",
        "surface-dim": "#0e0e0e",
        "tertiary-fixed": "#fd9d1a",
        "surface-container-low": "#131313",
        "primary-fixed": "#ff7763",
        "on-secondary-container": "#fff6f2",
        "surface-bright": "#2c2c2c",
        "error-container": "#a70138",
        "surface": "#0e0e0e",
        "tertiary-container": "#fd9d1a",
        "on-tertiary-fixed-variant": "#583300",
        "on-secondary": "#421e00",
        "primary": "#ff8e7d",
        "on-primary-fixed": "#000000",
        "primary-container": "#ff7763",
        "on-secondary-fixed-variant": "#7f3f00",
        "on-surface-variant": "#adaaaa",
        "outline-variant": "#484847",
        "primary-fixed-dim": "#f06955",
        "error-dim": "#d73357",
        "on-background": "#ffffff",
        "secondary-container": "#944a00",
        "on-error": "#490013",
        "on-primary-fixed-variant": "#600100",
        "surface-tint": "#ff8e7d"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "1rem", 
        "lg": "2rem", 
        "xl": "3rem", 
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
